# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb7b137d0ba60de03b4f808c454df60ca69d8ec9e35bbaa99da96ada3d3efbd1d612b7edc1627ccbc9e3a7543529623600c7dd890ae1f0e4715d79123f4d7eb2

test:
  secret_key_base: 2432cec245c1aec9a7f5f10aff3f33d9f4eca0e489497ade5afa5bd9cb5116cc100fa5003259d82b5f6c13f2b157d366c5f1f00bc58f032078569919be38f34a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
